# This is a basic workflow to help you get started with Actions

name: export-and-branch-solution

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    # Change this value
    inputs: 
      solution_name:
        description: 'name of the solution to worked on from Power Platform' 
        required: true 
        default: 'Session'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  export-from-dev:
    runs-on: windows-latest
    env:
      RUNNER DEBUG: 1
    steps:
    - uses: actions/checkout@v2 
      with:
        lfs: true
    
    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@0.4.0 
      with:
        environment-url: ${{env.ENYIRONMENT_URL}} 
        user-name: ${{env.USERNAME}}
        password-secret: ${{ secrets.password }}
    
    - name: export-solution action
      uses: microsoft/ -actions /export -solution@0.4.0 
      with:
        environment-url: ${{env.ENVIRONMENT_URL}} 
        user-name: ${{env.USERNAME}}
        password-secret: ${{ secrets.password }}
        solution-name: ${{ github.event.inputs.solution_name }}
        solution-output -file: ${{ github.event .inputs .solution_exported_folder}}/${{ github.event.inputs.solution_name }}.zip
    
    - name: unpack-solution action
      uses: microsoft/powerplatform-actions /unpack-solution@0.4.0 
      with:
        solution-file: ${{ github.event.inputs.solution_exported_folder}}/${{ github.event.inputs.solution_name }}.zip 
        solution-folder: ${{ github.event.inputs.solution_folder}}/${{ github.event.inputs.solution_name }}
        solution-type: 'Unmanaged'
        overwrite-files: true
    
    - name: branch-solution, prepare it for a PullRequest
      uses: microsoft/powerplatform-actions/branch-solution@0.4.0 
      with:
        solution-folder: ${{ github.event.inputs.solution_folder}}/${{ github.event.inputs.solution_name }}
        solution-target-folder: ${{ github.event.inputs.solution_target_folder}}/${{ github.event .inputs.solution_name }} 
        repo-token: ${{ secrets.GITHUB_TOKEN}} 
